### ISSUE TITLE
Selenium tests more than 5 minutes

### ISSUE THREAD

**Issue by PersianIronwood** [blackboard/lambda-selenium#30]
I am interested in using lambda-selenium. 
Our selenium tests currently take about an hour to run using webdriver. How your lambda functions will take care of our selenium tests since they only can live  for 5 minutes.?
Thanks

**Comment by wesmcouch** [comment]
In our framework, we have an annotation that we use label @NotLambda. The test runner runs the lambda and non-lambda tests concurrently. This allows you to choose where you want tests to run in the case of tests that run longer than 5 minutes. We have also worked to break up tests, and make them as short as possible to make running in lambda easy.

**Comment by PersianIronwood** [comment]
Thank you for the swift response. 
I am planning to run my selenium tests on perfecto , using a lambda function inside the AWS code pipeline.  I will try lambda-selenium.

**Comment by wesmcouch** [comment]
I have some big plans to move our actual test framework code into this repository to make it more widely available, but it will require some work to move internal settings into parameters and configurations to make it usable for others.
